apiVersion: apps/v1
kind: Deployment
metadata:
  name: worklog-ui
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: worklog-ui
  template:
    metadata:
      labels:
        app: worklog-ui
    spec:
      containers:
      - image: docker.io/divakar51/worklog-ui:latest
        name: worklog-ui
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"

---

apiVersion: v1
kind: Service
metadata:
  name: worklog-ui
spec:
  type: LoadBalancer
  selector:
    app: worklog-ui
  ports:
  - port: 3000
